name: Tests

on: push

jobs:
  yes_wip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'wip')"
    steps:
      - name: print github.event.head_commit.message
        run: |
          echo "${{ github.event.head_commit.message }}"

  no_wip:
    if: "contains(github.event.head_commit.message, '!wip')"
    runs-on: ubuntu-latest
    steps:
      - name: print github.event.head_commit.message
        run: |
          echo "${{ github.event.head_commit.message }}"
          echo "no wip"
