name: Tests

on: push

jobs:
  build:
    # if: "contains(github.event.head_commit.message, '!wip')"

    runs-on: ubuntu-latest

    steps:
      - name: print github.event.head_commit.message
        run: |
          echo "${{ github.event.head_commit.message }}"
